//
// Created by Hashara Kumarasinghe on 11/7/2025.
//

#ifndef POC_GPU_LIKELIHOOD_CALCULATIONS_LIKELIHOODCALCULATOR_H
#define POC_GPU_LIKELIHOOD_CALCULATIONS_LIKELIHOODCALCULATOR_H


class LikelihoodCalculator {

};


#endif //POC_GPU_LIKELIHOOD_CALCULATIONS_LIKELIHOODCALCULATOR_H
